namespace Jellyfin.Plugin.FinTV.Domain;

public enum ChannelContentType
{
    TvShow = 0,
    Movie = 1,
    MusicVideo = 2,
    Music = 3,
    Weather = 4
}

public enum AspectRatioMode
{
    SixteenNine = 0,
    FourThree = 1
}

public enum BugPlacementMode
{
    Auto = 0,
    TopLeft = 1,
    TopRight = 2,
    BottomLeft = 3,
    BottomRight = 4,
    None = 5
}

public enum FillerKind
{
    None = 0,
    PreRoll = 1,
    MidRoll = 2,
    PostRoll = 3
}

public enum LineupOverrideKind
{
    DayOfWeek = 0,
    SpecificDate = 1
}

public enum SlotCandidateKind
{
    JellyfinItem = 0,
    Collection = 1,
    FilterQuery = 2
}

public enum CommercialBreakMode
{
    ChaptersThenTimer = 0,
    TimerOnly = 1,
    ChaptersOnly = 2
}

public enum VirtualContentSource
{
    None = 0,
    WeatherStar = 1,
    MusicArtSlide = 2
}

public enum CommercialSource
{
    Jellyfin = 0,
    CommercialBrainz = 1
}

public enum CommercialPoolMode
{
    JellyfinOnly = 0,
    CommercialBrainzOnly = 1,
    Both = 2
}

public enum EbsBackgroundMusicSource
{
    /// <summary>
    /// Pick random tracks from all Jellyfin music libraries.
    /// </summary>
    AllMusicLibraries = 0,

    /// <summary>
    /// Pick random tracks from one selected music library.
    /// </summary>
    NamedLibrary = 1
}

public enum EbsSlateVariant
{
    /// <summary>
    /// USA off-air slate (<c>offlineusa.jpg</c>).
    /// </summary>
    Usa = 0,

    /// <summary>
    /// International off-air slate (<c>offline.jpg</c>).
    /// </summary>
    International = 1
}

public enum EbsDisplayMode
{
    /// <summary>
    /// Full-screen slate image from bundled stock or a custom upload.
    /// </summary>
    SlateImage = 0,

    /// <summary>
    /// SMPTE color bars generated by FFmpeg.
    /// </summary>
    ColorBars = 1,

    /// <summary>
    /// TV static/snow video generated by FFmpeg.
    /// </summary>
    Static = 2
}

public enum EbsAudioMode
{
    /// <summary>
    /// Random track from the configured Jellyfin music library.
    /// </summary>
    BackgroundMusic = 0,

    /// <summary>
    /// FFmpeg-generated white noise.
    /// </summary>
    WhiteNoise = 1,

    /// <summary>
    /// Silent stereo track.
    /// </summary>
    Silence = 2,

    /// <summary>
    /// Repeating alert beep tone.
    /// </summary>
    BeepTone = 3
}

public enum AiProvider
{
    OpenAi = 0,
    Venice = 1
}

public enum ChannelCatalogMode
{
    TvOnly = 0,
    MovieOnly = 1,
    Mixed = 2,
    MusicVideoOnly = 3
}
