<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>ChannelFlow.CommercialDetect</RootNamespace>
    <AssemblyName>ChannelFlow.CommercialDetect</AssemblyName>
    <Authors>binarygeek119</Authors>
    <Product>ChannelFlow Commercial Detect</Product>
    <Version>1.0.0</Version>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>

</Project>
