name: Build ChannelFlow-Server

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: recursive
      - uses: actions/setup-dotnet@v6
        with:
          dotnet-version: '10.0.x'
      - name: Publish server
        run: dotnet publish src/ChannelFlow.Server/ChannelFlow.Server.csproj -c Release /p:SkipLogoFetch=true
